version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes: 
      - db-data:/var/lib/postgresql/data
  api:
    build: .
    ports:
            - "8000:8080"
    environment:
        DATABASE.HOST: dba
        DATABASE.PORT: 5432
        DATABASE.NAME: ${POSTGRES_DB}
        DATABASE.USER: ${POSTGRES_USER}
        DATABASE.PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
        - db
volumes:
  db-data: