
spring:
  datasource:
    url: jdbc:postgresql://${ENDPOINT}:${PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa: 
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    hibernate.ddl-auto: create
  liquibase:
    enabled: false
